[project]
name = "sam3-2026-01-31"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "exif>=1.6.1",
    "ipywidgets>=8.1.8",
    "pandas>=3.0.0",
    "ultralytics>=8.4.9",
]
